- hosts: localhost
  become: true
  pre_tasks:
    - name: Update repositories
      apt: update_cache=yes
      changed_when: False
    - name: Upgrade all packages to the latest version
      apt:
        upgrade: safe
  vars:
    hostname: "xps-13"
    user: "nicola"
  tasks:
    - include: tasks/users.yml
    - include: tasks/system.yml
    - include: tasks/gnome.yml
    - include: tasks/repositories.yml
    # - include: tasks/cron.yml
    - include: tasks/apps/audio-video.yml
    - include: tasks/apps/developer-tools.yml
    - include: tasks/apps/graphics.yml
    - include: tasks/apps/internet.yml
    - include: tasks/apps/productivity.yml
    - include: tasks/apps/utilities.yml
    - include: tasks/docker.yml
    # - include: tasks/minikube.yml
