---
- name: Install Brave
  tags: browser
  block:
    - name: Brave> Add APT key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
        state: present
    - name: Brave> Add APT repository
      apt_repository:
        repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ ansible_distribution_release }} main
        state: present
        filename: brave-browser-apt-release
    - name: Brave> Update repositories
      apt: update_cache=yes
    - name: Brave> Install
      apt:
        name: "brave-browser"

- name: Install Chromium
  tags: browser
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra

- name: Install Google Chrome
  tags: browser
  block:
  - name: Google Chrome> Add APT key
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      state: present
  - name: Google Chrome> Add APT repository
    apt_repository:
      repo: deb http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: 'google-chrome'
  - name: Google Chrome> Install
    apt: 
      name: google-chrome-stable
      state: present 
      update_cache: yes

- name: Install Thunderbird
  tags: browser
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - thunderbird
    - thunderbird-gnome-support

- name: Install Skype
  tags: chat
  snap:
    name: skype
    classic: yes

- name: Install GIMP
  tags: graphics
  apt:
    name: gimp

- name: Install Spotify
  tags: multimedia
  snap:
    name: spotify

- name: Install VLC
  tags: multimedia
  snap:
    name: vlc

- name: Install FBReader
  tags: productivity
  apt:
    name: "fbreader"

- name: Install LibreOffice Base & extras
  tags: productivity
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libreoffice-base
    - libreoffice-base-drivers
    - libreoffice-dmaths
    - libreoffice-java-common
    - libreoffice-l10n-it
    - libreoffice-lightproof-en
    - libreoffice-mysql-connector
    - libreoffice-nlpsolver
    - libreoffice-report-builder
    - libreoffice-report-builder-bin
    - libreoffice-sdbc-firebird
    - libreoffice-sdbc-hsqldb
    - libreoffice-sdbc-postgresql
    - libreoffice-templates
    - mythes-it

# - name: Install LaTex
#   apt:
#     name: "{{ packages }}"
#   vars:
#     packages:
#     - ???

- name: Install BitWarden
  tags: [security, password]
  snap:
    name: bitwarden

- name: Install MEGAsync client
  tags: [backup]
  block:
    - name: MEGAsync> Add APT key
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: 8F208FBF12FEE766AA32AEAF03C3AD3A7F068E5D
    - name: MEGAsync> Add APT repository
      apt_repository:
        repo: deb https://mega.nz/linux/MEGAsync/xUbuntu_18.04/ ./
        state: present
        filename: 'megasync'
    - name: MEGAsync> Install
      apt: 
        name: megasync
        state: present
        update_cache: yes