- name: Install git
  tags: development
  apt:
    name: git

- name: Install OpenJDK 8
  tags: [development, java, scala]
  apt:
    name: openjdk-8-jdk

- name: Install OpenJDK 11
  tags: [development, java, scala]
  apt:
    name: openjdk-11-jdk

# TODO Set default Java using a variable (8, 11)
# https://docs.ansible.com/ansible/latest/modules/alternatives_module.html

- name: Install sbt
  tags: [development, scala]
  block:
  - name: Add sbt APT repository
    apt_repository:
      repo: deb https://dl.bintray.com/sbt/debian /
      state: present
      filename: sbt
  - name: Add sbt APT key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      state: present
  - name: Update APT repositories
    apt: update_cache=yes
  - name: Install sbt
    apt:
      name: "sbt"

- name: Install Meld
  tags: development
  apt:
    name: "meld"

- name: Install GNOME Builder
  tags: [development, editor, gnome]
  apt:
    name: "gnome-builder"

- name: Install Visual Studio Code
  tags: [development, editor]
  snap:
    name: code
    classic: yes

- name: Install DBeaver CE
  tags: [database, development, editor]
  snap:
    name: dbeaver-ce

- name: Install IntelliJ IDEA CE
  tags: [development, editor]
  snap:
    name: intellij-idea-community
    classic: yes