- name: Install git
  tags: development
  apt:
    name: git

- name: Install OpenJDK 8
  tags: [development, java, scala]
  apt:
    name: openjdk-8-jdk

- name: Install OpenJDK 11
  tags: [development, java, scala]
  apt:
    name: openjdk-11-jdk

# TODO Set default Java using a variable (8, 11)
# https://docs.ansible.com/ansible/latest/modules/alternatives_module.html

- name: Install sbt
  tags: [development, scala]
  block:
  - name: sbt> Add APT key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      keyring: /etc/apt/trusted.gpg.d/sbt.gpg
      state: present
  - name: sbt> Add APT repository
    apt_repository:
      repo: deb https://dl.bintray.com/sbt/debian /
      state: present
      filename: sbt
  - name: sbt> Update repositories
    apt: update_cache=yes
  - name: sbt> Install
    apt:
      name: sbt

- name: Install Meld
  tags: development
  apt:
    name: meld

- name: Install GNOME Builder
  tags: [development, editor, gnome]
  apt:
    name: gnome-builder

- name: Install Visual Studio Code
  tags: [development, editor]
  snap:
    name: code
    classic: yes

- name: Install DBeaver CE
  tags: [database, development, editor]
  block:
  - name: DBeaver> Add APT key
    apt_key:
      url: https://dbeaver.io/debs/dbeaver.gpg.key
      keyring: /etc/apt/trusted.gpg.d/dbeaver.gpg
      state: present
  - name: DBeaver> Add APT repository
    apt_repository:
      repo: deb https://dbeaver.io/debs/dbeaver-ce /
      state: present
      filename: dbeaver
  - name: DBeaver> Update repositories
    apt: update_cache=yes
  - name: DBeaver> Install
    apt:
      name: dbeaver-ce

- name: Install IntelliJ IDEA CE
  tags: [development, editor, java, scala]
  snap:
    name: intellij-idea-community
    classic: yes

- name: Install PyCharm CE
  tags: [development, editor, python]
  snap:
    name: pycharm-community
    classic: yes

- name: Install Postman
  tags: [development]
  snap:
    name: postman
    classic: yes