---
# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04

- name: Install requirements
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable
    state: present

- name: Update repositories
  apt: update_cache=yes

- name: Install Docker CE
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Create group 'docker'
  group:
    name: docker
    state: present

- name: Add user to group 'docker'
  user:
    name: "{{ user }}"
    group: docker
    append: yes

- name: Apply user changes
  meta: reset_connection

- name: Install Docker Module for Python
  pip:
    name: docker

  # Pull image specified by variable default_image from the Docker Hub
- name: Pull default Docker image
  become: yes
  become_user: "{{ user }}"
  docker_image:
    name: hello-world
    source: pull