- name: Install system utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - cryptsetup # Needed to access encrypted partitions
    - gdebi
    - synaptic
    - gnome-sushi
    - fslint

- name: Install power utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - lm-sensors
    - powertop

- name: Install development utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - git
    - openjdk-11-jdk
    - meld
  
- name: Install GIMP
  apt:
    name: "gimp"

- name: Install FBReader
  apt:
    name: "fbreader"

- name: Install LibreOffice Base & extras
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libreoffice-base
    - libreoffice-base-drivers
    - libreoffice-dmaths
    - libreoffice-java-common
    - libreoffice-l10n-it
    - libreoffice-lightproof-en
    - libreoffice-mysql-connector
    - libreoffice-nlpsolver
    - libreoffice-report-builder
    - libreoffice-report-builder-bin
    - libreoffice-sdbc-firebird
    - libreoffice-sdbc-hsqldb
    - libreoffice-sdbc-postgresql
    - libreoffice-templates
    - mythes-it

# - name: Install LaTex
#   apt:
#     name: "{{ packages }}"
#   vars:
#     packages:
#     - ???
