- name: Add PostgreSQL APT repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ distribution }}-pgdg main
    state: present
    filename: pgdg

- name: Add PostgreSQL APT key
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Update APT repositories
  apt: update_cache=yes

- name: Install PostgreSQL client
  apt:
    name: "postgresql-client-{{ psql.version }}"
