---
- name: Update hostname
  hostname:
    name: "{{ hostname }}"

- name: Update /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^127\.0\.1\.1'
    line: '127.0.1.1 {{ hostname }}'
    state: present

- name: Copy SSH config file
  copy: src=assets/ssh_config dest={{ ansible_user_dir }}/.ssh/config owner={{ ansible_user_id }} group={{ ansible_user_id }} mode=0400

# TODO Copy private/public SSH keys from a safe place (Ansible Vault / Ansible lookup module)

- name: Install system utilities
  tags: system
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - cryptsetup # Needed to access encrypted partitions
    - gdebi
    - synaptic
    - fslint

- name: Install power utilities
  tags: system
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - lm-sensors
    - powertop

- name: Install Ubuntu restricted extras
  tags: system
  apt:
    name: "ubuntu-restricted-extras"

# TODO Disable Bluetooth on startup
