- name: Install VirtualBox 6
  tags: virtualization
  block:
  - name: VirtualBox 6> Add APT key
    apt_key:
      url: "https://www.virtualbox.org/download/oracle_vbox_2016.asc"
      keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg
      state: present
  - name: VirtualBox 6> Add APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.virtualbox.org/virtualbox/debian {{ ansible_distribution_release }} contrib"
      state: present
      filename: virtualbox
  - name: VirtualBox 6> Update repositories
    apt:
      update_cache: yes
  - name: Virtualbox 6> Install
    apt:
      name: "virtualbox-6.0"


# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-18-04
- name: Install Docker
  tags: virtualization
  block:
    - name: Docker> Install requirements
      apt:
          name: "{{ packages }}"
      vars:
          packages:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
          - python-pip
    - name: Docker> Add APT key
      apt_key:
          url: https://download.docker.com/linux/ubuntu/gpg
          keyring: /etc/apt/trusted.gpg.d/docker.gpg
          state: present
    - name: Docker> Add APT repository
      apt_repository:
          repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
          state: present
          filename: docker
    - name: Docker> Update repositories
      apt: 
        update_cache: yes
    - name: Docker> Install
      apt:
          name: "{{ packages }}"
      vars:
          packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io
    - name: Docker> Create group 'docker'
      group:
          name: docker
          state: present
    - name: Docker> Add user to group 'docker'
      user:
          name: "{{ user }}"
          groups: docker
          append: yes


# https://minikube.sigs.k8s.io/docs/start/linux/
- name: Install minikube
  tags: [virtualization]
  block:
    - name: minikube> Check virtualization support
      shell: "egrep -q 'vmx|svm' /proc/cpuinfo && echo yes || echo no"
      register: "virt"
      failed_when: "virt.stdout == 'no'"
    - name: minikube> Download package
      get_url:
        url: "https://storage.googleapis.com/minikube/releases/latest/minikube_{{ minikube_version }}.deb"
        dest: "{{ ansible_user_dir }}/minikube.deb"
    - name: minikube> Install package
      apt:
        deb: "{{ ansible_user_dir }}/minikube.deb"
  rescue:
    - debug:
        msg: "minikube installation failed since virtualization support is not available or enabled"
  always:
    - name: minikube> Delete package file
      file:
        state: absent
        path: "{{ ansible_user_dir }}/minikube.deb"


# - name: Install MicroK8s
#   snap:
#     name: microk8s
#     classic: yes