- name: Install PostgreSQL
  tags: [development, database]
  block:
  - name: PostgreSQL> Add APT key
    apt_key:
      url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
      keyring: /etc/apt/trusted.gpg.d/pgdg.gpg
      state: present
  - name: PostgreSQL> Add APT repository
    apt_repository:
      repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
      state: present
      filename: pgdg
  - name: PostgreSQL> Install PostgreSQL client
    apt:
      name: "postgresql-client-{{ psql_version }}"
      update_cache: yes