- name: Install sbt
  tags: [development, scala]
  block:
  - name: sbt> Add APT key
    apt_key:
      keyserver: hkp://keyserver.ubuntu.com:80
      id: 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      keyring: /etc/apt/trusted.gpg.d/sbt.gpg
      state: present
  - name: sbt> Add APT repository
    apt_repository:
      repo: deb https://dl.bintray.com/sbt/debian /
      state: present
      filename: sbt
  - name: sbt> Install
    apt:
      name: sbt
      update_cache: yes