---
- name: Install Chromium
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - chromium-browser
    - chromium-browser-l10n
    - chromium-codecs-ffmpeg-extra

- name: Install Brave
  block:
    - name: Add Brave GPG key
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        keyring: /etc/apt/trusted.gpg.d/brave-browser-release.gpg
        state: present
    - name: Add Brave repository
      apt_repository:
      repo: deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ distribution }} main
      state: present
    - name: Update repositories
      apt: update_cache=yes
    - name: Install Brave
      apt:
        name: "brave-browser"

- name: Install Skype
  snap:
    name: skype
    classic: yes