---
- name: Install BitWarden
  snap:
    name: bitwarden

- name: Install system utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - cryptsetup # Needed to access encrypted partitions
    - gdebi
    - synaptic
    - fslint

- name: Install power utilities
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - lm-sensors
    - powertop