- name: Install LibreOffice Base & extras
  tags: [office suite, productivity]
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - libreoffice-base
    - libreoffice-base-drivers
    - libreoffice-dmaths
    - libreoffice-java-common
    - libreoffice-l10n-it
    - libreoffice-lightproof-en
    - libreoffice-mysql-connector
    - libreoffice-nlpsolver
    - libreoffice-report-builder
    - libreoffice-report-builder-bin
    - libreoffice-sdbc-firebird
    - libreoffice-sdbc-hsqldb
    - libreoffice-sdbc-postgresql
    - libreoffice-templates
    - mythes-it