- name: Install Google Chrome
  tags: browser
  block:
  - name: Google Chrome> Add APT key
    apt_key:
      url: https://dl.google.com/linux/linux_signing_key.pub
      keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg
      state: present
  - name: Google Chrome> Add APT repository
    apt_repository:
      repo: deb http://dl.google.com/linux/chrome/deb/ stable main
      state: present
      filename: 'google-chrome'
  - name: Google Chrome> Install
    apt: 
      name: google-chrome-stable
      state: present 
      update_cache: yes